// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Keys = require("./keys");
var Cashscript = require("cashscript");
var TimedTimeoutJson = require("./json/TimedTimeout.json");

var artifact = TimedTimeoutJson;

var keys = Keys;

function run(param) {
  var provider = new Cashscript.ElectrumNetworkProvider("mainnet");
  var constructorArgs = [
    keys.alicePk,
    keys.bobPk
  ];
  new Cashscript.ElectrumNetworkProvider(artifact, constructorArgs, provider);
  
}

exports.artifact = artifact;
exports.keys = keys;
exports.run = run;
/* artifact Not a pure module */
